version: '3'
services:
    backend:
        image: ${'USER_DOCKER_HUB'}/${'REPO_BACK_DOCKER_HUB'}:${'VERSION'}
        ports:
            - "8000:8000"
        container_name: backend
        networks:
            - atos242-backend-network

networks:
    atos242-backend-network:
        driver: bridge
