version: '3'
services:
    backend:
        build:
            context: .
            dockerfile: enoove/atos242-backend:0.1.0
        container_name: backend
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - .:/var/www/backend/html
            - ./docker/local/app.conf:/etc/nginx/sites-enabled/default
        networks:
            - atos242-backend-network
        ports:
            - 8000:8000
        depends_on:
            - mysql

    mysql:
        image: 'mysql/mysql-server:8.0.1'
        container_name: mysql8.0.1
        ports:
            - '${DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            #MYSQL_USER: '${DB_USERNAME}'
            #MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql:/var/lib/mysql'
        networks:
            - atos242-backend-network
networks:
    atos242-backend-network:
        driver: bridge
volumes:
    mysql:
        driver: local
