version: '3'
services:
    backend:
        image: enoove/atos242-backend:00.00.024
        ports:
            - "8000:8000"
        container_name: backend
        networks:
            - atos242-backend-network

networks:
    atos242-backend-network:
        driver: bridge
